// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220110.5

#pragma once
#ifndef WINRT_Microsoft_Windows_ApplicationModel_WindowsAppRuntime_1_H
#define WINRT_Microsoft_Windows_ApplicationModel_WindowsAppRuntime_1_H
#include "winrt/impl/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.0.h"
WINRT_EXPORT namespace winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime
{
    struct __declspec(empty_bases) IDeploymentInitializeOptions :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDeploymentInitializeOptions>
    {
        IDeploymentInitializeOptions(std::nullptr_t = nullptr) noexcept {}
        IDeploymentInitializeOptions(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IDeploymentInitializeOptions2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDeploymentInitializeOptions2>
    {
        IDeploymentInitializeOptions2(std::nullptr_t = nullptr) noexcept {}
        IDeploymentInitializeOptions2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IDeploymentManagerStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDeploymentManagerStatics>
    {
        IDeploymentManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IDeploymentManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IDeploymentManagerStatics2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDeploymentManagerStatics2>
    {
        IDeploymentManagerStatics2(std::nullptr_t = nullptr) noexcept {}
        IDeploymentManagerStatics2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IDeploymentResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDeploymentResult>
    {
        IDeploymentResult(std::nullptr_t = nullptr) noexcept {}
        IDeploymentResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IDeploymentResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDeploymentResultFactory>
    {
        IDeploymentResultFactory(std::nullptr_t = nullptr) noexcept {}
        IDeploymentResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
