// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220110.5

#pragma once
#ifndef WINRT_Microsoft_Graphics_Display_1_H
#define WINRT_Microsoft_Graphics_Display_1_H
#include "winrt/impl/Microsoft.Graphics.Display.0.h"
WINRT_EXPORT namespace winrt::Microsoft::Graphics::Display
{
    struct __declspec(empty_bases) IDisplayAdvancedColorInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDisplayAdvancedColorInfo>
    {
        IDisplayAdvancedColorInfo(std::nullptr_t = nullptr) noexcept {}
        IDisplayAdvancedColorInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IDisplayInformation :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDisplayInformation>
    {
        IDisplayInformation(std::nullptr_t = nullptr) noexcept {}
        IDisplayInformation(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IDisplayInformationStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDisplayInformationStatics>
    {
        IDisplayInformationStatics(std::nullptr_t = nullptr) noexcept {}
        IDisplayInformationStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
